#!/bin/sh
# Add your startup script

# DO NOT DELETE

# Dynamic flag generated by CTFd-whale
chown root:ctf /home/ctf/flag

chmod +x /home/ctf/rsa1.py

/home/ctf/rsa1.py
trap : TERM INT; 
sleep infinity & wait\

